title: RetroflagGpi Guides
description: Useful guides for Retroflag Gpi Case
image: https://github.com/SinisterSpatula/RetroflagGpiGuides/raw/master/assets/images/preview.png
theme: jekyll-theme-hacker
plugins:
  - jekyll-seo-tag
header:
  image: /assets/images/preview.png
  og_image: /assets/images/preview.png
